server:
  port: 8081

# --- Redis Connection ---
spring:
  data:
    redis:
      host: amc-app-prod-elastic-cache-redis-1.miaqyf.ng.0001.aps1.cache.amazonaws.com
      port: 6379
      cache:
        timeToLive: 86400 # 1 day in seconds
#  main:
#    allow-bean-definition-overriding: true # Good to have during development
  web:
    client:
      resttemplate:
        connect-timeout: 5s # You can use duration units like 's' for seconds
        read-timeout: 10s
  mail:
    host: smtp.gmail.com
    port: 587
    username: chaudharys666@gmail.com
    password: nbdytgxmxvanpkrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# --- Email Alerting ---
alerting:
  mail:
    to: sarvesh.chaudhary@deptagency.com
    from: chaudharys666@gmail.com


# --- AEM Integration ---
aem:
  api:
    username: springboot-user
    password: MySecurePassword123
    url:
      baseurl: https://author-p143654-e1482275.adobeaemcloud.com
      individualFundURL: /content/aem-cloud-dept-backend-motilal-oswal/api/fund.json
      filteredCFFundsURL: /content/aem-cloud-dept-backend-motilal-oswal/api/funds-filtered-data.json
      individualFundManagerURL: /content/aem-cloud-dept-backend-motilal-oswal/api/fund-manager.json
      pmsListingURL: /content/aem-cloud-dept-backend-motilal-oswal/api/pms-strategies.json
      pmsStrategyURL: /content/aem-cloud-dept-backend-motilal-oswal/api/pms-strategies-by-schcode.json
      pmsManagerURL: /content/aem-cloud-dept-backend-motilal-oswal/api/pms-manager.json

# --- External APIs ---
motilaloswal:
  api:
    url:
      performanceGraphNew: https://www.motilaloswalmf.com/mutualfund/api/v1/PerformanceGraphNew

# --- API Security ---
api:
  security:
    aem-key: AEM_KEY_12345

# OpenSearch Config
opensearch:
  hostname: 10.4.51.214
  port: 9200
  scheme: http
  index-name: aem-pages

# -- Adobe Configuration (Prod) --
adobe:
  ims:
    clientId: prod-client-id       # fallback to dummy if not set
    clientSecret: prod-secret      # fallback value
    scope: AdobeID,openid,aem_cloud_api
    token:
      url: https://ims-na1-stg1.adobelogin.com/ims/token/v3
